# -*- coding: utf-8 -*-
"""Python exercise 2: Travel Pony Ad Cost Regression Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CKJoPv4e0vrZQRBEFAKF6CG6J-rru9Xi
"""

import pandas as pd
import numpy as np 
from google.colab import drive
!pip install arrow as arrow
import arrow as arrow
import statsmodels.api as sm

drive.mount('/content/drive')

csvfile = 'drive/My Drive/Colab Notebooks/Travel Pony Facebook.csv'
travelpony = pd.read_csv(csvfile)
travelpony.head()

"""Remove 0's for amount spent"""

travelpony=travelpony[travelpony['Amount Spent (USD)']!=0]

"""Graph a histogramof Amount Spent using Seaborn"""

import seaborn as sns
sns.set_style('darkgrid')
sns.distplot(travelpony['Amount Spent (USD)'])

"""Create a scatter plot for spend and: reach, frequency, impressions and clicks."""

sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Reach'])

sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Frequency'])

sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Impressions'])

sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Clicks'])

"""Combined scatterplots below, harder to read."""

sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Reach'])
sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Frequency'])
sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Impressions'])
sns.scatterplot(travelpony['Amount Spent (USD)'],travelpony['Clicks'])

travelpony['Campaign Name'].unique()

travelpony['Campaign Name']= travelpony['Campaign Name'].astype('str')
travelpony['Campaign Name']= travelpony['Campaign Name'].str.replace('[^a-zA-Z0-9:\s+]','')
travelpony['Campaign Name']= travelpony['Campaign Name'].str.replace('\d+','')

pd.get_dummies(travelpony['Campaign Name'])
travelpony = pd.concat([travelpony,pd.get_dummies(travelpony['Campaign Name'])],axis=1)
travelpony.head()

"""Build a multiple regression with an outcome variable of Amount Spent and predictor variables: Campaign Name, Reach, Frequency, Impressions, Clicks, Unique Clicks, Page Likes, Page Engagement, Post Engagement, Post Likes, Post Comments, Post Shares, Photo Views, Website Clicks"""

y = travelpony['Amount Spent (USD)']
x = travelpony[['Ad ','Cyber Weekend','Nanigans','Post: You need to get some real sun and we are here to','SimpleMultiFillCampaign','TravelPony: Conversion Test','TravelPony: General Ads','TravelponyPage LikesUS','http:travelponyClicksUS','Reach','Frequency','Impressions','Clicks','Unique Clicks','Page Likes','Page Engagement','Post Engagement','Post Likes','Post Comments','Post Shares','Photo Views','Website Clicks']]
model = sm.OLS(y,x.astype(float)).fit()
predictions=model.predict(x)
model.summary()

"""Looking at the coefficents of the predictor variables, TravelPony: Conversion Test, Page Like, and Post Engagement have the highest coefficent, respectively."""